blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://stackoverflow.com/tags/spring-data
    about: Please ask and answer questions on StackOverflow with the tag `spring-data`.
